### ISSUE TITLE
Fix .upload_filecount height

### ISSUE THREAD

**Issue by kkovalev** [Heroes-Profile/heroesprofile-api-public#53]
It is broken. Just watch my screenshots:

<img width="1280" alt="Снимок экрана 2021-03-16 в 01 09 12" src="https://user-images.githubusercontent.com/11396467/111237760-c5b79280-8606-11eb-989a-3ddf7c656f58.png">
<img width="1280" alt="Снимок экрана 2021-03-16 в 01 09 00" src="https://user-images.githubusercontent.com/11396467/111237749-c2240b80-8606-11eb-8c25-291830c4226e.png">

**Comment by Zemill** [comment]
Resovled
